version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-node8-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions 
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Java Tests
          command: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-store
      - store_artifacts:
          path: fudi-store/build/reports
          destination: reports
      - store_test_results:
          path: fudi-store/build/test-results
      - run:
          name: Run Kotlin Tests 
          command: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-store-kotlin
      - store_artifacts:
          path: fudi-store-kotlin/build/reports
          destination: reports
      - store_test_results:
          path: fudi-store-kotlin/build/test-results

#